# Generated by Django 5.1.1 on 2024-10-03 11:47

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0003_alter_spell_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=pathlib.PureWindowsPath('D:/py_projects/Com pro 1/SpezSpellz/content')),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pathlib.PureWindowsPath('D:/py_projects/Com pro 1/SpezSpellz/content'))),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spezspellz.spell')),
            ],
        ),
        migrations.CreateModel(
            name='SpellNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('every', models.CharField(choices=[('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('Y', 'Year'), ('S', 'Single')], default='S', max_length=1)),
                ('message', models.CharField(max_length=256)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spezspellz.spell')),
            ],
        ),
    ]
