# Generated by Django 5.1.1 on 2024-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0005_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='notification',
            new_name='review_comment_notification',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='privacy',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='spell_comment_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='spell_review_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='timed_notification',
            field=models.BooleanField(default=True),
        ),
    ]
