# Generated by Django 5.1.1 on 2024-10-10 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0006_rename_notification_userinfo_review_comment_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='content'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='content'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_desc',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.CreateModel(
            name='SpellHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spezspellz.spell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ]
        )
    ]
