# Generated by Django 5.1.1 on 2024-10-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_desc',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.SmallIntegerField(),
        ),
    ]
