# Generated by Django 5.1.1 on 2024-10-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0008_userinfo_private'),
        ('spezspellz', '0012_remove_hastag_rating_ratecategory_ratetag'),
    ]

    operations = [
    ]
