# Generated by Django 5.1.1 on 2024-10-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0014_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='last_notified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
