# Generated by Django 5.1.1 on 2024-10-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0015_bookmark_last_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='last_notified',
        ),
    ]
