# Generated by Django 5.1.1 on 2024-10-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0018_remove_bookmark_last_notified_userinfo_last_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='unread_notifications',
            field=models.JSONField(default=list),
        ),
    ]
