# Generated by Django 5.1.1 on 2024-10-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0019_userinfo_unread_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='unread_notifications',
        ),
    ]
