# Generated by Django 5.1.1 on 2024-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ref',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.URLField(null=True),
        ),
    ]
