# Generated by Django 5.1.1 on 2024-11-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0023_userinfo_comment_reply_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualFileModel',
            fields=[
                ('path', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('data', models.BinaryField(max_length=50000000)),
            ],
        ),
    ]
