# Generated by Django 5.1.1 on 2024-11-13 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0026_tagrequest_ratetagrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
