# Generated by Django 5.1.1 on 2024-11-24 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spezspellz', '0028_success'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='success',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='success',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='success',
            name='user',
        ),
        migrations.CreateModel(
            name='SuccessRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spezspellz.spell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'spell')},
            },
        ),
        migrations.DeleteModel(
            name='RateSuccess',
        ),
        migrations.DeleteModel(
            name='Success',
        ),
    ]
